### PR TITLE
Hc 279 Remove deprecated HySDS code

### PR DESCRIPTION
**Pull request by DustinKLo**
https://hysds-core.atlassian.net/browse/HC-279

### CODE REVIEW

**Review by pymonger — DISMISSED** [review]

**Review by mcayanan — COMMENTED** [review]
Looks good. Just curious though, have you tried building a PCM container with these changes to make sure it didn't break anything?

https://github.jpl.nasa.gov/IEMS-SDS/nisar-pcm/blob/f9ad10804ebe4f23e6d78f4adc51494db6c6ba75/cluster_provisioning/run_smoke_test.sh#L40-L42

**Comment by DustinKLo** [comment]
@mcayanan  havent tested it yet, whats the best way to test it?

**Comment by mcayanan** [comment]
On the nisar ci machine, you'll probably need to deploy the container builder update on there and run those commands I linked you to in order to build the PCM container using your changes. When deploying the container builder update on nisar ci, be sure to back up the existing copy that's on there in case there's a bug so you can revert back to it. I don't know if there's an easier way. @pymonger ?

**Comment by DustinKLo** [comment]
@mcayanan @pymonger was able to test by cloning `container-builder` in to our CI instance (but changed the name to `container-builder-HC-279`)
```
$ pwd
/export/home/###/verdi/ops/container-builder-HC-279
(verdi) [###@nisar-pcm-ci container-builder-HC-279]$ git branch
* HC-279
  master
```

i used branch `HC-279` to build `lightweight-jobs` into my cluster
```
sds ci add_job -k -b develop https://github.com/hysds/lightweight-jobs.git s3
```

i also updated the jenkins build script to point to the new `container-builder` directory
```
# build image
if [ ! -z "$CONTAINER_REGISTRY" -a ! -z "$CONTAINER_REGISTRY_BUCKET" ]
then
  /export/home/####/verdi/ops/container-builder-HC-279/build-container.bash \
  ${REPO} ${TAG} ${STORAGE} ${MOZART_REST_URL} ${GRQ_REST_URL} ${SKIP_PUBLISH} ${CONTAINER_REGISTRY} --build-arg GIT_OAUTH_TOKEN=${GIT_OAUTH_TOKEN} --build-arg BRANCH=${TAG} --build-arg PCM_COMMONS_BRANCH=${PCM_COMMONS_BRANCH}
else
  /export/home/####/verdi/ops/container-builder-HC-279/build-container.bash \
  ${REPO} ${TAG} ${STORAGE} ${MOZART_REST_URL} ${GRQ_REST_URL} ${SKIP_PUBLISH} "" --build-arg GIT_OAUTH_TOKEN=${GIT_OAUTH_TOKEN} --build-arg BRANCH=${TAG} --build-arg PCM_COMMONS_BRANCH=${PCM_COMMONS_BRANCH}
fi
```

output: https://nisar-pcm-ci.jpl.nasa.gov/job/nisar-dustinlo-3_container-builder_hysds_lightweight-jobs_develop/1/console

Screen Shot 2020-10-26 at 1 25 57 PM

```
Started by user Dustin K Lo
Running as SYSTEM
Building in workspace /var/lib/jenkins/workspace/nisar-dustinlo-3_container-builder_hysds_lightweight-jobs_develop
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
No credentials specified
Cloning the remote Git repository
Cloning repository https://########@github.com/hysds/lightweight-jobs.git
 > git init /var/lib/jenkins/workspace/nisar-dustinlo-3_container-builder_hysds_lightweight-jobs_develop # timeout=10
Fetching upstream changes from https://########@github.com/hysds/lightweight-jobs.git
 > git --version # timeout=10
 > git --version # 'git version 1.8.3.1'
 > git fetch --tags --progress https://########@github.com/hysds/lightweight-jobs.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://########@github.com/hysds/lightweight-jobs.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://########@github.com/hysds/lightweight-jobs.git # timeout=10
Fetching upstream changes from https://########@github.com/hysds/lightweight-jobs.git
 > git fetch --tags --progress https://########@github.com/hysds/lightweight-jobs.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/develop^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/develop^{commit} # timeout=10
Checking out Revision ac556d7f1bee59b35e46505aea148056b080882a (refs/remotes/origin/develop)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f ac556d7f1bee59b35e46505aea148056b080882a # timeout=10
Commit message: "add purge.sh wrapper and disable python bytecode writing (#22)"
First time build. Skipping changelog.
[nisar-dustinlo-3_container-builder_hysds_lightweight-jobs_develop] $ /bin/bash /tmp/jenkins6187129903951178771.sh
+ '[' '!' -z localhost:5050 -a '!' -z nisar-pcm-registry-bucket ']'
+ /export/home/######/verdi/ops/container-builder-HC-279/build-container.bash hysds_lightweight-jobs develop s3://s3-us-west-2.amazonaws.com/nisar-dev-cc-fwd-dustinlo/ http://###.##.###.###:8888/api/v0.1 http://###.##.###.###:8878/api/v0.1 noskip localhost:5050 --build-arg GIT_OAUTH_TOKEN=######## --build-arg BRANCH=develop --build-arg PCM_COMMONS_BRANCH=develop
[CI] Is checkout a tag: 1 v1.0.5
[CI] Last log: commit ac556d7f1bee59b35e46505aea148056b080882a
Author: Gerald Manipon <pymonger@gmail.com>
Date:   Tue Oct 6 08:34:49 2020 -0700

    add purge.sh wrapper and disable python bytecode writing (#22)
[CI] Skip image build flag: 0
Validating job-spec for lightweight-echo
Validating hysds-io for lightweight-echo
Checking that the job-spec and hysds-io define the same parameters
Validating job-spec for lw-mozart-notify-by-email
Validating hysds-io for lw-mozart-notify-by-email
Checking that the job-spec and hysds-io define the same parameters
Validating job-spec for lw-mozart-purge
Validating hysds-io for lw-mozart-purge
Checking that the job-spec and hysds-io define the same parameters
Validating job-spec for lw-mozart-reprioritize
Validating hysds-io for lw-mozart-reprioritize
Checking that the job-spec and hysds-io define the same parameters
Validating job-spec for lw-mozart-retry
Validating hysds-io for lw-mozart-retry
Checking that the job-spec and hysds-io define the same parameters
Validating job-spec for lw-mozart-revoke
Validating hysds-io for lw-mozart-revoke
Checking that the job-spec and hysds-io define the same parameters
Validating job-spec for lw-tosca-aws_get
Validating hysds-io for lw-tosca-aws_get
Checking that the job-spec and hysds-io define the same parameters
Validating job-spec for lw-tosca-notify-by-email
Validating hysds-io for lw-tosca-notify-by-email
Checking that the job-spec and hysds-io define the same parameters
Validating job-spec for lw-tosca-purge
Validating hysds-io for lw-tosca-purge
Checking that the job-spec and hysds-io define the same parameters
Validating job-spec for lw-tosca-wget
Validating hysds-io for lw-tosca-wget
Checking that the job-spec and hysds-io define the same parameters
Validating job-spec for lw-tosca-wget-email
Validating hysds-io for lw-tosca-wget-email
Checking that the job-spec and hysds-io define the same parameters
Validating job-spec for lw-tosca-wget-glob
Validating hysds-io for lw-tosca-wget-glob
Checking that the job-spec and hysds-io define the same parameters
Validating job-spec for lw-tosca-wget-product
Validating hysds-io for lw-tosca-wget-product
Checking that the job-spec and hysds-io define the same parameters
All hysds-io and job-specs are valid
[CI] Build for: container-hysds_lightweight-jobs:develop and file hysds_lightweight-jobs
 docker build --rm --force-rm -f docker/Dockerfile -t container-hysds_lightweight-jobs:develop --build-arg GIT_OAUTH_TOKEN=######## --build-arg BRANCH=develop --build-arg PCM_COMMONS_BRANCH=develop .
Sending build context to Docker daemon  392.7kB

Step 1/8 : FROM hysds/pge-base:develop
 ---> bb23b2fe4a88
Step 2/8 : MAINTAINER malarout "Namrata.Malarout@jpl.nasa.gov"
 ---> Using cache
 ---> b7ee939ccccb
Step 3/8 : LABEL description="Lightweight System Jobs"
 ---> Using cache
 ---> fc35bcf73cb1
Step 4/8 : USER ops
 ---> Using cache
 ---> 94642a731e02
Step 5/8 : COPY . /home/ops/lightweight-jobs
 ---> e216987d015b
Step 6/8 : ENTRYPOINT ["/entrypoint-pge-with-stats.sh"]
 ---> Running in d5407deaccd9
Removing intermediate container d5407deaccd9
 ---> 75bbced4c1f8
Step 7/8 : WORKDIR /home/ops
 ---> Running in d12870e5aba7
Removing intermediate container d12870e5aba7
 ---> 2020d6a017eb
Step 8/8 : CMD ["/bin/bash", "--login"]
 ---> Running in 9a4ce87f261b
Removing intermediate container 9a4ce87f261b
 ---> 06b35a3fd47d
[Warning] One or more build-args [PCM_COMMONS_BRANCH BRANCH GIT_OAUTH_TOKEN] were not consumed
Successfully built 06b35a3fd47d
Successfully tagged container-hysds_lightweight-jobs:develop
[CI] Pushing docker container container-hysds_lightweight-jobs:develop to localhost:5050
The push refers to repository [localhost:5050/container-hysds_lightweight-jobs]
2c02a5bf78aa: Preparing
8018683c3d46: Preparing
542bfce5c667: Preparing
3f4ca92e2a04: Preparing
fd262f1ffcae: Preparing
0527db030176: Preparing
3388fe6b1854: Preparing
bad99a3c3d04: Preparing
613be09ab3c0: Preparing
bad99a3c3d04: Waiting
0527db030176: Waiting
613be09ab3c0: Waiting
3388fe6b1854: Waiting
3f4ca92e2a04: Layer already exists
8018683c3d46: Layer already exists
542bfce5c667: Layer already exists
fd262f1ffcae: Layer already exists
0527db030176: Layer already exists
bad99a3c3d04: Layer already exists
613be09ab3c0: Layer already exists
3388fe6b1854: Layer already exists
2c02a5bf78aa: Pushed
develop: digest: sha256:9e0c51ebeed46b81b64d93e241cd52abe5444ac0c092abc4d1f2e3c8ba513fff size: 2206
[CI] Build for: job-lightweight-echo:develop and file lightweight-echo
Running Job-Met on: container-hysds_lightweight-jobs:develop docker/job-spec.json.lightweight-echo develop job-lightweight-echo:develop
[CI] Build for: job-lw-mozart-notify-by-email:develop and file lw-mozart-notify-by-email
Running Job-Met on: container-hysds_lightweight-jobs:develop docker/job-spec.json.lw-mozart-notify-by-email develop job-lw-mozart-notify-by-email:develop
[CI] Build for: job-lw-mozart-purge:develop and file lw-mozart-purge
Running Job-Met on: container-hysds_lightweight-jobs:develop docker/job-spec.json.lw-mozart-purge develop job-lw-mozart-purge:develop
[CI] Build for: job-lw-mozart-reprioritize:develop and file lw-mozart-reprioritize
Running Job-Met on: container-hysds_lightweight-jobs:develop docker/job-spec.json.lw-mozart-reprioritize develop job-lw-mozart-reprioritize:develop
[CI] Build for: job-lw-mozart-retry:develop and file lw-mozart-retry
Running Job-Met on: container-hysds_lightweight-jobs:develop docker/job-spec.json.lw-mozart-retry develop job-lw-mozart-retry:develop
[CI] Build for: job-lw-mozart-revoke:develop and file lw-mozart-revoke
Running Job-Met on: container-hysds_lightweight-jobs:develop docker/job-spec.json.lw-mozart-revoke develop job-lw-mozart-revoke:develop
[CI] Build for: job-lw-tosca-aws_get:develop and file lw-tosca-aws_get
Running Job-Met on: container-hysds_lightweight-jobs:develop docker/job-spec.json.lw-tosca-aws_get develop job-lw-tosca-aws_get:develop
[CI] Build for: job-lw-tosca-notify-by-email:develop and file lw-tosca-notify-by-email
Running Job-Met on: container-hysds_lightweight-jobs:develop docker/job-spec.json.lw-tosca-notify-by-email develop job-lw-tosca-notify-by-email:develop
[CI] Build for: job-lw-tosca-purge:develop and file lw-tosca-purge
Running Job-Met on: container-hysds_lightweight-jobs:develop docker/job-spec.json.lw-tosca-purge develop job-lw-tosca-purge:develop
[CI] Build for: job-lw-tosca-wget:develop and file lw-tosca-wget
Running Job-Met on: container-hysds_lightweight-jobs:develop docker/job-spec.json.lw-tosca-wget develop job-lw-tosca-wget:develop
[CI] Build for: job-lw-tosca-wget-email:develop and file lw-tosca-wget-email
Running Job-Met on: container-hysds_lightweight-jobs:develop docker/job-spec.json.lw-tosca-wget-email develop job-lw-tosca-wget-email:develop
[CI] Build for: job-lw-tosca-wget-glob:develop and file lw-tosca-wget-glob
Running Job-Met on: container-hysds_lightweight-jobs:develop docker/job-spec.json.lw-tosca-wget-glob develop job-lw-tosca-wget-glob:develop
[CI] Build for: job-lw-tosca-wget-product:develop and file lw-tosca-wget-product
Running Job-Met on: container-hysds_lightweight-jobs:develop docker/job-spec.json.lw-tosca-wget-product develop job-lw-tosca-wget-product:develop
[CI] Build for: hysds-io-lightweight-echo:develop and file lightweight-echo
Running IO-Met on: container-hysds_lightweight-jobs:develop docker/hysds-io.json.lightweight-echo develop hysds-io-lightweight-echo:develop
404 Client Error: NOT FOUND for url: http://###.##.###.###:8878/api/v0.1/hysds_io/type
[CI] Build for: hysds-io-lw-mozart-notify-by-email:develop and file lw-mozart-notify-by-email
Running IO-Met on: container-hysds_lightweight-jobs:develop docker/hysds-io.json.lw-mozart-notify-by-email develop hysds-io-lw-mozart-notify-by-email:develop
404 Client Error: NOT FOUND for url: http://###.##.###.###:8888/api/v0.1/hysds_io/type
[CI] Build for: hysds-io-lw-mozart-purge:develop and file lw-mozart-purge
Running IO-Met on: container-hysds_lightweight-jobs:develop docker/hysds-io.json.lw-mozart-purge develop hysds-io-lw-mozart-purge:develop
404 Client Error: NOT FOUND for url: http://###.##.###.###:8888/api/v0.1/hysds_io/type
[CI] Build for: hysds-io-lw-mozart-reprioritize:develop and file lw-mozart-reprioritize
Running IO-Met on: container-hysds_lightweight-jobs:develop docker/hysds-io.json.lw-mozart-reprioritize develop hysds-io-lw-mozart-reprioritize:develop
404 Client Error: NOT FOUND for url: http://###.##.###.###:8888/api/v0.1/hysds_io/type
[CI] Build for: hysds-io-lw-mozart-retry:develop and file lw-mozart-retry
Running IO-Met on: container-hysds_lightweight-jobs:develop docker/hysds-io.json.lw-mozart-retry develop hysds-io-lw-mozart-retry:develop
404 Client Error: NOT FOUND for url: http://###.##.###.###:8888/api/v0.1/hysds_io/type
[CI] Build for: hysds-io-lw-mozart-revoke:develop and file lw-mozart-revoke
Running IO-Met on: container-hysds_lightweight-jobs:develop docker/hysds-io.json.lw-mozart-revoke develop hysds-io-lw-mozart-revoke:develop
404 Client Error: NOT FOUND for url: http://###.##.###.###:8888/api/v0.1/hysds_io/type
[CI] Build for: hysds-io-lw-tosca-aws_get:develop and file lw-tosca-aws_get
Running IO-Met on: container-hysds_lightweight-jobs:develop docker/hysds-io.json.lw-tosca-aws_get develop hysds-io-lw-tosca-aws_get:develop
404 Client Error: NOT FOUND for url: http://###.##.###.###:8878/api/v0.1/hysds_io/type
[CI] Build for: hysds-io-lw-tosca-notify-by-email:develop and file lw-tosca-notify-by-email
Running IO-Met on: container-hysds_lightweight-jobs:develop docker/hysds-io.json.lw-tosca-notify-by-email develop hysds-io-lw-tosca-notify-by-email:develop
404 Client Error: NOT FOUND for url: http://###.##.###.###:8878/api/v0.1/hysds_io/type
[CI] Build for: hysds-io-lw-tosca-purge:develop and file lw-tosca-purge
Running IO-Met on: container-hysds_lightweight-jobs:develop docker/hysds-io.json.lw-tosca-purge develop hysds-io-lw-tosca-purge:develop
404 Client Error: NOT FOUND for url: http://###.##.###.###:8878/api/v0.1/hysds_io/type
[CI] Build for: hysds-io-lw-tosca-wget:develop and file lw-tosca-wget
Running IO-Met on: container-hysds_lightweight-jobs:develop docker/hysds-io.json.lw-tosca-wget develop hysds-io-lw-tosca-wget:develop
404 Client Error: NOT FOUND for url: http://###.##.###.###:8878/api/v0.1/hysds_io/type
[CI] Build for: hysds-io-lw-tosca-wget-email:develop and file lw-tosca-wget-email
Running IO-Met on: container-hysds_lightweight-jobs:develop docker/hysds-io.json.lw-tosca-wget-email develop hysds-io-lw-tosca-wget-email:develop
404 Client Error: NOT FOUND for url: http://###.##.###.###:8878/api/v0.1/hysds_io/type
[CI] Build for: hysds-io-lw-tosca-wget-glob:develop and file lw-tosca-wget-glob
Running IO-Met on: container-hysds_lightweight-jobs:develop docker/hysds-io.json.lw-tosca-wget-glob develop hysds-io-lw-tosca-wget-glob:develop
404 Client Error: NOT FOUND for url: http://###.##.###.###:8878/api/v0.1/hysds_io/type
[CI] Build for: hysds-io-lw-tosca-wget-product:develop and file lw-tosca-wget-product
Running IO-Met on: container-hysds_lightweight-jobs:develop docker/hysds-io.json.lw-tosca-wget-product develop hysds-io-lw-tosca-wget-product:develop
404 Client Error: NOT FOUND for url: http://###.##.###.###:8878/api/v0.1/hysds_io/type
+ '[' -f ./docker/extract_artifacts.sh ']'
Recording test results
None of the test reports contained any result
Finished: SUCCESS
```

**Comment by mcayanan** [comment]
@DustinKLo I might be missing something, but do you know why you were getting those 404 errors when building a job?

**Comment by DustinKLo** [comment]
> @DustinKLo I might be missing something, but do you know why you were getting those 404 errors when building a job?

it's because in `io-met.py` (`add_hysds_io` function) it calls the GRQ/Mozart rest API and checks if the `hysds-io` (with version) document exists
and its returning a `404` because we don't have `lightweight-jobs:develop` PGEs built into our clusters

```
    try:
        req = requests.get(hysds_io_endpoint, data=hysds_io_obj, verify=False)
        req.raise_for_status()
        doc = req.json()
    except Exception as e:
        doc = None
        print(e)  # ignore errors
```

**Comment by DustinKLo** [comment]
@mcayanan  i re-ran the jenkins job and it's not printing a `404` error because the container was already built earlier

```
>>> try:
...     r = requests.get("http://localhost:8888/api/v0.1/hysds_io/type?id=fjskjlk")
...     r.raise_for_status()
... except Exception as e:
...     print(e)
... 
404 Client Error: NOT FOUND for url: http://localhost:8888/api/v0.1/hysds_io/type?id=fjskjlk
```

```
Started by user Dustin K Lo
Running as SYSTEM
Building in workspace /var/lib/jenkins/workspace/nisar-######-3_container-builder_hysds_lightweight-jobs_develop
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
[WS-CLEANUP] Done
No credentials specified
Cloning the remote Git repository
Cloning repository https://###########@github.com/hysds/lightweight-jobs.git
 > git init /var/lib/jenkins/workspace/nisar-######-3_container-builder_hysds_lightweight-jobs_develop # timeout=10
Fetching upstream changes from https://###########@github.com/hysds/lightweight-jobs.git
 > git --version # timeout=10
 > git --version # 'git version 1.8.3.1'
 > git fetch --tags --progress https://###########@github.com/hysds/lightweight-jobs.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://###########@github.com/hysds/lightweight-jobs.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://###########@github.com/hysds/lightweight-jobs.git # timeout=10
Fetching upstream changes from https://###########@github.com/hysds/lightweight-jobs.git
 > git fetch --tags --progress https://###########@github.com/hysds/lightweight-jobs.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/develop^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/develop^{commit} # timeout=10
Checking out Revision ac556d7f1bee59b35e46505aea148056b080882a (refs/remotes/origin/develop)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f ac556d7f1bee59b35e46505aea148056b080882a # timeout=10
Commit message: "add purge.sh wrapper and disable python bytecode writing (#22)"
 > git rev-list --no-walk ac556d7f1bee59b35e46505aea148056b080882a # timeout=10
[nisar-######-3_container-builder_hysds_lightweight-jobs_develop] $ /bin/bash /tmp/jenkins1153634780853696808.sh
+ '[' '!' -z localhost:5050 -a '!' -z nisar-pcm-registry-bucket ']'
+ /export/home/#######/verdi/ops/container-builder-HC-279/build-container.bash hysds_lightweight-jobs develop s3://s3-us-west-2.amazonaws.com/nisar-dev-cc-fwd-######/ http://###.##.###.###:8888/api/v0.1 http://###.##.###.###:8878/api/v0.1 noskip localhost:5050 --build-arg GIT_OAUTH_TOKEN=########### --build-arg BRANCH=develop --build-arg PCM_COMMONS_BRANCH=develop
[CI] Is checkout a tag: 1 v1.0.5
[CI] Last log: commit ac556d7f1bee59b35e46505aea148056b080882a
Author: Gerald Manipon <pymonger@gmail.com>
Date:   Tue Oct 6 08:34:49 2020 -0700

    add purge.sh wrapper and disable python bytecode writing (#22)
[CI] Skip image build flag: 0
Validating job-spec for lightweight-echo
Validating hysds-io for lightweight-echo
Checking that the job-spec and hysds-io define the same parameters
Validating job-spec for lw-mozart-notify-by-email
Validating hysds-io for lw-mozart-notify-by-email
Checking that the job-spec and hysds-io define the same parameters
Validating job-spec for lw-mozart-purge
Validating hysds-io for lw-mozart-purge
Checking that the job-spec and hysds-io define the same parameters
Validating job-spec for lw-mozart-reprioritize
Validating hysds-io for lw-mozart-reprioritize
Checking that the job-spec and hysds-io define the same parameters
Validating job-spec for lw-mozart-retry
Validating hysds-io for lw-mozart-retry
Checking that the job-spec and hysds-io define the same parameters
Validating job-spec for lw-mozart-revoke
Validating hysds-io for lw-mozart-revoke
Checking that the job-spec and hysds-io define the same parameters
Validating job-spec for lw-tosca-aws_get
Validating hysds-io for lw-tosca-aws_get
Checking that the job-spec and hysds-io define the same parameters
Validating job-spec for lw-tosca-notify-by-email
Validating hysds-io for lw-tosca-notify-by-email
Checking that the job-spec and hysds-io define the same parameters
Validating job-spec for lw-tosca-purge
Validating hysds-io for lw-tosca-purge
Checking that the job-spec and hysds-io define the same parameters
Validating job-spec for lw-tosca-wget
Validating hysds-io for lw-tosca-wget
Checking that the job-spec and hysds-io define the same parameters
Validating job-spec for lw-tosca-wget-email
Validating hysds-io for lw-tosca-wget-email
Checking that the job-spec and hysds-io define the same parameters
Validating job-spec for lw-tosca-wget-glob
Validating hysds-io for lw-tosca-wget-glob
Checking that the job-spec and hysds-io define the same parameters
Validating job-spec for lw-tosca-wget-product
Validating hysds-io for lw-tosca-wget-product
Checking that the job-spec and hysds-io define the same parameters
All hysds-io and job-specs are valid
[CI] Removing current image for container-hysds_lightweight-jobs:develop: 06b35a3fd47d
Total reclaimed space: 0B
Untagged: container-hysds_lightweight-jobs:develop
Untagged: localhost:5050/container-hysds_lightweight-jobs:develop
Untagged: localhost:5050/container-hysds_lightweight-jobs@sha256:9e0c51ebeed46b81b64d93e241cd52abe5444ac0c092abc4d1f2e3c8ba513fff
Deleted: sha256:06b35a3fd47de44aa85ce850841a77d771666d94ba3799019156203b90c765e7
Deleted: sha256:2020d6a017eb0dbaba4f20e0942cc3f9c69e5b55d2732045decdb5640d0e6a79
Deleted: sha256:75bbced4c1f8416c59b5f7a63c3df43ad38d627de3d18ae62a901e1993cf56de
Deleted: sha256:e216987d015bf00f5b46defffcec6b13da7ca7324221bd01724b7d001d7d0e0f
Deleted: sha256:09f7379072e782f187cdaf63856f30e0d3af5143db9fe96aabb0e172f662721b
[CI] Build for: container-hysds_lightweight-jobs:develop and file hysds_lightweight-jobs
 docker build --rm --force-rm -f docker/Dockerfile -t container-hysds_lightweight-jobs:develop --build-arg GIT_OAUTH_TOKEN=########### --build-arg BRANCH=develop --build-arg PCM_COMMONS_BRANCH=develop .
Sending build context to Docker daemon  392.7kB

Step 1/8 : FROM hysds/pge-base:develop
 ---> bb23b2fe4a88
Step 2/8 : MAINTAINER malarout "Namrata.Malarout@jpl.nasa.gov"
 ---> Using cache
 ---> b7ee939ccccb
Step 3/8 : LABEL description="Lightweight System Jobs"
 ---> Using cache
 ---> fc35bcf73cb1
Step 4/8 : USER ops
 ---> Using cache
 ---> 94642a731e02
Step 5/8 : COPY . /home/ops/lightweight-jobs
 ---> f0834c8bed85
Step 6/8 : ENTRYPOINT ["/entrypoint-pge-with-stats.sh"]
 ---> Running in 64740b746542
Removing intermediate container 64740b746542
 ---> 52cf8157504c
Step 7/8 : WORKDIR /home/ops
 ---> Running in 7014c9e3341a
Removing intermediate container 7014c9e3341a
 ---> 21b3700453b8
Step 8/8 : CMD ["/bin/bash", "--login"]
 ---> Running in 5d37d5ccef47
Removing intermediate container 5d37d5ccef47
 ---> 25d52297cd53
[Warning] One or more build-args [BRANCH GIT_OAUTH_TOKEN PCM_COMMONS_BRANCH] were not consumed
Successfully built 25d52297cd53
Successfully tagged container-hysds_lightweight-jobs:develop
[CI] Pushing docker container container-hysds_lightweight-jobs:develop to localhost:5050
The push refers to repository [localhost:5050/container-hysds_lightweight-jobs]
d73110d0ca50: Preparing
8018683c3d46: Preparing
542bfce5c667: Preparing
3f4ca92e2a04: Preparing
fd262f1ffcae: Preparing
0527db030176: Preparing
3388fe6b1854: Preparing
bad99a3c3d04: Preparing
613be09ab3c0: Preparing
0527db030176: Waiting
3388fe6b1854: Waiting
bad99a3c3d04: Waiting
613be09ab3c0: Waiting
542bfce5c667: Layer already exists
fd262f1ffcae: Layer already exists
3f4ca92e2a04: Layer already exists
8018683c3d46: Layer already exists
3388fe6b1854: Layer already exists
bad99a3c3d04: Layer already exists
0527db030176: Layer already exists
613be09ab3c0: Layer already exists
d73110d0ca50: Pushed
develop: digest: sha256:d6856449b8458c03509c9167c99fb87021591ab2e459142082772ac0dc73e6b2 size: 2206
[CI] Build for: job-lightweight-echo:develop and file lightweight-echo
Running Job-Met on: container-hysds_lightweight-jobs:develop docker/job-spec.json.lightweight-echo develop job-lightweight-echo:develop
[CI] Build for: job-lw-mozart-notify-by-email:develop and file lw-mozart-notify-by-email
Running Job-Met on: container-hysds_lightweight-jobs:develop docker/job-spec.json.lw-mozart-notify-by-email develop job-lw-mozart-notify-by-email:develop
[CI] Build for: job-lw-mozart-purge:develop and file lw-mozart-purge
Running Job-Met on: container-hysds_lightweight-jobs:develop docker/job-spec.json.lw-mozart-purge develop job-lw-mozart-purge:develop
[CI] Build for: job-lw-mozart-reprioritize:develop and file lw-mozart-reprioritize
Running Job-Met on: container-hysds_lightweight-jobs:develop docker/job-spec.json.lw-mozart-reprioritize develop job-lw-mozart-reprioritize:develop
[CI] Build for: job-lw-mozart-retry:develop and file lw-mozart-retry
Running Job-Met on: container-hysds_lightweight-jobs:develop docker/job-spec.json.lw-mozart-retry develop job-lw-mozart-retry:develop
[CI] Build for: job-lw-mozart-revoke:develop and file lw-mozart-revoke
Running Job-Met on: container-hysds_lightweight-jobs:develop docker/job-spec.json.lw-mozart-revoke develop job-lw-mozart-revoke:develop
[CI] Build for: job-lw-tosca-aws_get:develop and file lw-tosca-aws_get
Running Job-Met on: container-hysds_lightweight-jobs:develop docker/job-spec.json.lw-tosca-aws_get develop job-lw-tosca-aws_get:develop
[CI] Build for: job-lw-tosca-notify-by-email:develop and file lw-tosca-notify-by-email
Running Job-Met on: container-hysds_lightweight-jobs:develop docker/job-spec.json.lw-tosca-notify-by-email develop job-lw-tosca-notify-by-email:develop
[CI] Build for: job-lw-tosca-purge:develop and file lw-tosca-purge
Running Job-Met on: container-hysds_lightweight-jobs:develop docker/job-spec.json.lw-tosca-purge develop job-lw-tosca-purge:develop
[CI] Build for: job-lw-tosca-wget:develop and file lw-tosca-wget
Running Job-Met on: container-hysds_lightweight-jobs:develop docker/job-spec.json.lw-tosca-wget develop job-lw-tosca-wget:develop
[CI] Build for: job-lw-tosca-wget-email:develop and file lw-tosca-wget-email
Running Job-Met on: container-hysds_lightweight-jobs:develop docker/job-spec.json.lw-tosca-wget-email develop job-lw-tosca-wget-email:develop
[CI] Build for: job-lw-tosca-wget-glob:develop and file lw-tosca-wget-glob
Running Job-Met on: container-hysds_lightweight-jobs:develop docker/job-spec.json.lw-tosca-wget-glob develop job-lw-tosca-wget-glob:develop
[CI] Build for: job-lw-tosca-wget-product:develop and file lw-tosca-wget-product
Running Job-Met on: container-hysds_lightweight-jobs:develop docker/job-spec.json.lw-tosca-wget-product develop job-lw-tosca-wget-product:develop
[CI] Build for: hysds-io-lightweight-echo:develop and file lightweight-echo
Running IO-Met on: container-hysds_lightweight-jobs:develop docker/hysds-io.json.lightweight-echo develop hysds-io-lightweight-echo:develop
[CI] Build for: hysds-io-lw-mozart-notify-by-email:develop and file lw-mozart-notify-by-email
Running IO-Met on: container-hysds_lightweight-jobs:develop docker/hysds-io.json.lw-mozart-notify-by-email develop hysds-io-lw-mozart-notify-by-email:develop
[CI] Build for: hysds-io-lw-mozart-purge:develop and file lw-mozart-purge
Running IO-Met on: container-hysds_lightweight-jobs:develop docker/hysds-io.json.lw-mozart-purge develop hysds-io-lw-mozart-purge:develop
[CI] Build for: hysds-io-lw-mozart-reprioritize:develop and file lw-mozart-reprioritize
Running IO-Met on: container-hysds_lightweight-jobs:develop docker/hysds-io.json.lw-mozart-reprioritize develop hysds-io-lw-mozart-reprioritize:develop
[CI] Build for: hysds-io-lw-mozart-retry:develop and file lw-mozart-retry
Running IO-Met on: container-hysds_lightweight-jobs:develop docker/hysds-io.json.lw-mozart-retry develop hysds-io-lw-mozart-retry:develop
[CI] Build for: hysds-io-lw-mozart-revoke:develop and file lw-mozart-revoke
Running IO-Met on: container-hysds_lightweight-jobs:develop docker/hysds-io.json.lw-mozart-revoke develop hysds-io-lw-mozart-revoke:develop
[CI] Build for: hysds-io-lw-tosca-aws_get:develop and file lw-tosca-aws_get
Running IO-Met on: container-hysds_lightweight-jobs:develop docker/hysds-io.json.lw-tosca-aws_get develop hysds-io-lw-tosca-aws_get:develop
[CI] Build for: hysds-io-lw-tosca-notify-by-email:develop and file lw-tosca-notify-by-email
Running IO-Met on: container-hysds_lightweight-jobs:develop docker/hysds-io.json.lw-tosca-notify-by-email develop hysds-io-lw-tosca-notify-by-email:develop
[CI] Build for: hysds-io-lw-tosca-purge:develop and file lw-tosca-purge
Running IO-Met on: container-hysds_lightweight-jobs:develop docker/hysds-io.json.lw-tosca-purge develop hysds-io-lw-tosca-purge:develop
[CI] Build for: hysds-io-lw-tosca-wget:develop and file lw-tosca-wget
Running IO-Met on: container-hysds_lightweight-jobs:develop docker/hysds-io.json.lw-tosca-wget develop hysds-io-lw-tosca-wget:develop
[CI] Build for: hysds-io-lw-tosca-wget-email:develop and file lw-tosca-wget-email
Running IO-Met on: container-hysds_lightweight-jobs:develop docker/hysds-io.json.lw-tosca-wget-email develop hysds-io-lw-tosca-wget-email:develop
[CI] Build for: hysds-io-lw-tosca-wget-glob:develop and file lw-tosca-wget-glob
Running IO-Met on: container-hysds_lightweight-jobs:develop docker/hysds-io.json.lw-tosca-wget-glob develop hysds-io-lw-tosca-wget-glob:develop
[CI] Build for: hysds-io-lw-tosca-wget-product:develop and file lw-tosca-wget-product
Running IO-Met on: container-hysds_lightweight-jobs:develop docker/hysds-io.json.lw-tosca-wget-product develop hysds-io-lw-tosca-wget-product:develop
+ '[' -f ./docker/extract_artifacts.sh ']'
Recording test results
None of the test reports contained any result
Finished: SUCCESS
```

**Review by mcayanan — APPROVED** [review]
LGTM. Thanks for testing this.

**Pull request merged**
